import 'package:flutter/foundation.dart';

class AppLocalization {
  // Global language state ('EN' or 'HI')
  static final ValueNotifier<String> currentLang = ValueNotifier<String>('EN');

  static void toggleLanguage() {
    if (currentLang.value == 'EN') {
      currentLang.value = 'HI';
    } else {
      currentLang.value = 'EN';
    }
  }

  static void setLanguage(String lang) {
    if (lang == 'EN' || lang == 'HI') {
      currentLang.value = lang;
    }
  }

  // Helper method to get string based on current language
  static String get(String key) {
    final lang = currentLang.value;
    if (_dictionary.containsKey(key)) {
      return _dictionary[key]![lang] ?? key;
    }
    return key; // Fallback to key if not found
  }

  // Quick translation dictionary for prototype
  static final Map<String, Map<String, String>> _dictionary = {
    // Shared
    'Road Repair Assistance': {'EN': 'Road Repair Assistance', 'HI': 'सड़क मरम्मत सहायता'},
    'Public Works • Janakpuri': {'EN': 'Public Works • Janakpuri', 'HI': 'सार्वजनिक कार्य • जनकपुरी'},
    'Sep 26–30': {'EN': 'Sep 26–30', 'HI': '26-30 सितंबर'},
    '12 workers': {'EN': '12 workers', 'HI': '12 कामगार'},
    'Masonry': {'EN': 'Masonry', 'HI': 'चिनाई'},
    'General Labour': {'EN': 'General Labour', 'HI': 'सामान्य श्रम'},
    'Job Done': {'EN': 'Job Done', 'HI': 'काम पूरा'},
    'Co-op Paid': {'EN': 'Co-op Paid', 'HI': 'को-ऑप को भुगतान'},
    'Deduction': {'EN': 'Deduction', 'HI': 'कटौती'},
    'Total:': {'EN': 'Total:', 'HI': 'कुल:'},
    'Worker Mobile Verification\n': {'EN': 'Worker Mobile Verification\n', 'HI': 'कामगार मोबाइल सत्यापन\n'},
    'This OTP verifies your mobile number. Your profile and skills will be verified on the next step.': {'EN': 'This OTP verifies your mobile number. Your profile and skills will be verified on the next step.', 'HI': 'यह ओटीपी आपके मोबाइल नंबर की पुष्टि करता है। अगले चरण में आपकी प्रोफ़ाइल और कौशल सत्यापित किए जाएंगे।'},
    'This Year': {'EN': 'This Year', 'HI': 'इस वर्ष'},
    '🏠 Household • Dwarka': {'EN': '🏠 Household • Dwarka', 'HI': '🏠 परिवार • द्वारका'},
    'Sep 10, 2026': {'EN': 'Sep 10, 2026', 'HI': '10 सितंबर 2026'},
    '🏢 Institution • Najafgarh': {'EN': '🏢 Institution • Najafgarh', 'HI': '🏢 संस्थान • नजफगढ़'},
    'Sep 5, 2026': {'EN': 'Sep 5, 2026', 'HI': '5 सितंबर 2026'},
    'Electrical Maintenance': {'EN': 'Electrical Maintenance', 'HI': 'इलेक्ट्रिकल रखरखाव'},
    '🏢 Institution • Janakpuri': {'EN': '🏢 Institution • Janakpuri', 'HI': '🏢 संस्थान • जनकपुरी'},
    'Aug 28, 2026': {'EN': 'Aug 28, 2026', 'HI': '28 अगस्त 2026'},
    'Need attention': {'EN': 'Need attention', 'HI': 'ध्यान देने की आवश्यकता'},
    'Safety Issues': {'EN': 'Safety Issues', 'HI': 'सुरक्षा मुद्दे'},
    'Assistance Requests': {'EN': 'Assistance Requests', 'HI': 'सहायता अनुरोध'},
    'Needs Attention': {'EN': 'Needs Attention', 'HI': 'ध्यान देने की आवश्यकता'},
    '⚠ Safety Issue': {'EN': '⚠ Safety Issue', 'HI': '⚠ सुरक्षा मुद्दा'},
    'Sunita Devi': {'EN': 'Sunita Devi', 'HI': 'सुनीता देवी'},
    'Safety equipment required before next assignment.': {'EN': 'Safety equipment required before next assignment.', 'HI': 'अगले काम से पहले सुरक्षा उपकरण आवश्यक।'},
    '💰 Pending Payment': {'EN': '💰 Pending Payment', 'HI': '💰 लंबित भुगतान'},
    'Payment pending for ₹1,200.': {'EN': 'Payment pending for ₹1,200.', 'HI': '₹1,200 का भुगतान लंबित।'},
    'Coming soon:': {'EN': 'Coming soon:', 'HI': 'जल्द आ रहा है:'},
    'Plumbing': {'EN': 'Plumbing', 'HI': 'प्लंबिंग'},
    'Electrical': {'EN': 'Electrical', 'HI': 'इलेक्ट्रिकल'},
    'Painting': {'EN': 'Painting', 'HI': 'पेंटिंग'},
    'Carpentry': {'EN': 'Carpentry', 'HI': 'बढ़ईगिरी'},
    'Cleaning': {'EN': 'Cleaning', 'HI': 'सफाई'},
    'Gardening': {'EN': 'Gardening', 'HI': 'बागवानी'},
    'Construction': {'EN': 'Construction', 'HI': 'निर्माण'},
    'You have accepted this opportunity.': {'EN': 'You have accepted this opportunity.', 'HI': 'आपने इस अवसर को स्वीकार कर लिया है।'},
    'You have declined this opportunity.': {'EN': 'You have declined this opportunity.', 'HI': 'आपने इस अवसर को अस्वीकार कर दिया है।'},
    'Simulated Verification Successful': {'EN': 'Simulated Verification Successful', 'HI': 'सिम्युलेटेड सत्यापन सफल'},
    'Simulated Verification Failed: Invalid UAN': {'EN': 'Simulated Verification Failed: Invalid UAN', 'HI': 'सिम्युलेटेड सत्यापन विफल: अमान्य UAN'},
    'Verify with e-Shram (Simulated) →': {'EN': 'Verify with e-Shram (Simulated) →', 'HI': 'ई-श्रम से सत्यापित करें (सिम्युलेटेड) →'},
    'Note: This is a simulated verification for demo purposes.': {'EN': 'Note: This is a simulated verification for demo purposes.', 'HI': 'नोट: यह डेमो उद्देश्यों के लिए एक सिम्युलेटेड सत्यापन है।'},
    'Back': {'EN': 'Back', 'HI': 'पीछे'},
    'EN': {'EN': 'EN', 'HI': 'EN'},
    'हिन्दी': {'EN': 'हिन्दी', 'HI': 'हिन्दी'},
    'Paid': {'EN': 'Paid', 'HI': 'भुगतान किया'},
    'Pending': {'EN': 'Pending', 'HI': 'लंबित'},
    
    // 13C - Earnings & Payments
    'Earnings & Payments': {'EN': 'Earnings & Payments', 'HI': 'कमाई और भुगतान'},
    'Track project earnings and worker payments.': {'EN': 'Track project earnings and worker payments.', 'HI': 'परियोजना की कमाई और श्रमिक भुगतान को ट्रैक करें।'},
    'Payments Processed ✓': {'EN': 'Payments Processed ✓', 'HI': 'भुगतान संसाधित ✓'},
    'Pending worker payments have been marked for processing.': {'EN': 'Pending worker payments have been marked for processing.', 'HI': 'लंबित श्रमिक भुगतानों को प्रसंस्करण के लिए चिह्नित किया गया है।'},
    'Total': {'EN': 'Total', 'HI': 'कुल'},
    'This Month': {'EN': 'This Month', 'HI': 'इस महीने'},
    'Worker Paid': {'EN': 'Worker Paid', 'HI': 'श्रमिक भुगतान'},
    'To be processed': {'EN': 'To be processed', 'HI': 'संसाधित किया जाना है'},
    'Recent Project Earnings': {'EN': 'Recent Project Earnings', 'HI': 'हालिया परियोजना कमाई'},
    'Projects': {'EN': 'Projects', 'HI': 'परियोजनाएं'},
    'Upcoming': {'EN': 'Upcoming', 'HI': 'आगामी'},
    'Worker payments:': {'EN': 'Worker payments:', 'HI': 'श्रमिक भुगतान:'},
    'Completed': {'EN': 'Completed', 'HI': 'पूरा हुआ'},
    'In Progress': {'EN': 'In Progress', 'HI': 'प्रगति पर'},
    'Worker Payment Status': {'EN': 'Worker Payment Status', 'HI': 'श्रमिक भुगतान स्थिति'},
    'records': {'EN': 'records', 'HI': 'रिकॉर्ड'},
    'Transparent Payment Flow': {'EN': 'Transparent Payment Flow', 'HI': 'पारदर्शी भुगतान प्रवाह'},
    
    // 14C - Cooperative Exchange
    'Cooperative Exchange': {'EN': 'Cooperative Exchange', 'HI': 'सहकारी विनिमय'},
    'Share resources. Find opportunities. Grow together.': {'EN': 'Share resources. Find opportunities. Grow together.', 'HI': 'संसाधन साझा करें। अवसर खोजें। एक साथ बढ़ें।'},
    'Work Opps': {'EN': 'Work Opps', 'HI': 'कार्य अवसर'},
    'Workforce': {'EN': 'Workforce', 'HI': 'कार्यबल'},
    'Equipment': {'EN': 'Equipment', 'HI': 'उपकरण'},
    'Available Opportunities': {'EN': 'Available Opportunities', 'HI': 'उपलब्ध अवसर'},
    'Open': {'EN': 'Open', 'HI': 'खुला'},
    'SCHEDULE': {'EN': 'SCHEDULE', 'HI': 'अनुसूची'},
    'WORKFORCE REQ.': {'EN': 'WORKFORCE REQ.', 'HI': 'कार्यबल आवश्यकता'},
    'Skills:': {'EN': 'Skills:', 'HI': 'कौशल:'},
    'View Opportunity →': {'EN': 'View Opportunity →', 'HI': 'अवसर देखें →'},
    
    // 15C - AI Workforce Insights
    'AI Workforce Insights': {'EN': 'AI Workforce Insights', 'HI': 'एआई कार्यबल अंतर्दृष्टि'},
    'AI-Assisted': {'EN': 'AI-Assisted', 'HI': 'एआई-सहायता प्राप्त'},
    'Use demand trends to plan your workforce.': {'EN': 'Use demand trends to plan your workforce.', 'HI': 'अपने कार्यबल की योजना बनाने के लिए मांग प्रवृत्तियों का उपयोग करें।'},
    'Demand Forecast': {'EN': 'Demand Forecast', 'HI': 'मांग पूर्वानुमान'},
    'Next 7 Days': {'EN': 'Next 7 Days', 'HI': 'अगले 7 दिन'},
    'Weekly Outlook': {'EN': 'Weekly Outlook', 'HI': 'साप्ताहिक आउटलुक'},
    'next week': {'EN': 'next week', 'HI': 'अगले सप्ताह'},
    'Forecast Confidence': {'EN': 'Forecast Confidence', 'HI': 'पूर्वानुमान विश्वास'},
    
    // 16C - Reports & Work History
    'Reports & Work History': {'EN': 'Reports & Work History', 'HI': 'रिपोर्ट और कार्य इतिहास'},
    'Review completed work and cooperative performance.': {'EN': 'Review completed work and cooperative performance.', 'HI': 'पूरे किए गए कार्य और सहकारी प्रदर्शन की समीक्षा करें।'},
    'Workers': {'EN': 'Workers', 'HI': 'श्रमिक'},
    'Project Value': {'EN': 'Project Value', 'HI': 'परियोजना मूल्य'},
    'All': {'EN': 'All', 'HI': 'सभी'},
    'Recent Projects': {'EN': 'Recent Projects', 'HI': 'हालिया परियोजनाएं'},
    
    // 17C - Worker Welfare & Issues
    'Worker Welfare & Issues': {'EN': 'Worker Welfare & Issues', 'HI': 'श्रमिक कल्याण और मुद्दे'},
    'Support worker wellbeing, safety and timely assistance.': {'EN': 'Support worker wellbeing, safety and timely assistance.', 'HI': 'श्रमिक भलाई, सुरक्षा और समय पर सहायता का समर्थन करें।'},
    'Pending Payments': {'EN': 'Pending Payments', 'HI': 'लंबित भुगतान'},
    'Active': {'EN': 'Active', 'HI': 'सक्रिय'},
    // Home Screen (Welcome Page)
    'COOPERATIVE / सहकारी संस्था': {'EN': 'COOPERATIVE / सहकारी संस्था', 'HI': 'सहकारी संस्था / COOPERATIVE'},
    'Welcome to SAHYOG': {'EN': 'Welcome to SAHYOG', 'HI': 'सहयोग में आपका स्वागत है'},
    'Connect your cooperative with more work opportunities.': {'EN': 'Connect your cooperative with more work opportunities.', 'HI': 'अपनी सहकारी संस्था को अधिक कार्य अवसरों से जोड़ें।'},
    'Manage your workforce, receive service requests, assign workers, discover new opportunities, and track earnings — all in one place.': {'EN': 'Manage your workforce, receive service requests, assign workers, discover new opportunities, and track earnings — all in one place.', 'HI': 'अपने कार्यबल का प्रबंधन करें, सेवा अनुरोध प्राप्त करें, श्रमिकों को काम सौंपें, नए अवसर खोजें, और कमाई ट्रैक करें — सब एक ही स्थान पर।'},
    'With SAHYOG, your cooperative can': {'EN': 'With SAHYOG, your cooperative can', 'HI': 'सहयोग के साथ, आपकी सहकारी संस्था कर सकती है'},
    'Manage your workers and their availability': {'EN': 'Manage your workers and their availability', 'HI': 'अपने श्रमिकों और उनकी उपलब्धता का प्रबंधन करें'},
    'Receive household and institution service requests': {'EN': 'Receive household and institution service requests', 'HI': 'घरेलू और संस्थान सेवा अनुरोध प्राप्त करें'},
    'Match the right workers to each job': {'EN': 'Match the right workers to each job', 'HI': 'प्रत्येक काम के लिए सही श्रमिकों का मिलान करें'},
    'Discover opportunities through Cooperative Exchange': {'EN': 'Discover opportunities through Cooperative Exchange', 'HI': 'सहकारी विनिमय के माध्यम से अवसर खोजें'},
    'Track projects, payments and workforce performance': {'EN': 'Track projects, payments and workforce performance', 'HI': 'परियोजनाओं, भुगतानों और कार्यबल प्रदर्शन को ट्रैक करें'},
    'Empower workers. Build opportunities. Grow together.': {'EN': 'Empower workers. Build opportunities. Grow together.', 'HI': 'श्रमिकों को सशक्त बनाएं। अवसर बनाएं। एक साथ बढ़ें।'},
    'Login →': {'EN': 'Login →', 'HI': 'लॉगिन →'},
    '+ Create Cooperative Account': {'EN': '+ Create Cooperative Account', 'HI': '+ सहकारी खाता बनाएं'},
    'COOPERATE. EMPOWER. GROW. / साथ मिलकर, समृद्धि की ओर': {'EN': 'COOPERATE. EMPOWER. GROW. / साथ मिलकर, समृद्धि की ओर', 'HI': 'साथ मिलकर, समृद्धि की ओर / COOPERATE. EMPOWER. GROW.'},
    
    // Dashboard Screen
    'Good morning, Nirman Shramik 👋': {'EN': 'Good morning, Nirman Shramik 👋', 'HI': 'सुप्रभात, निर्माण श्रमिक 👋'},
    'Manage your workforce, requests and opportunities.': {'EN': 'Manage your workforce, requests and opportunities.', 'HI': 'अपने कार्यबल, अनुरोधों और अवसरों का प्रबंधन करें।'},
    'Cooperative Verified': {'EN': 'Cooperative Verified', 'HI': 'सहकारी सत्यापित'},
    '👷 Workers': {'EN': '👷 Workers', 'HI': '👷 श्रमिक'},
    '28 Available': {'EN': '28 Available', 'HI': '28 उपलब्ध'},
    '📋 Active Jobs': {'EN': '📋 Active Jobs', 'HI': '📋 सक्रिय नौकरियां'},
    '5 Pending Requests': {'EN': '5 Pending Requests', 'HI': '5 लंबित अनुरोध'},
    '💰 Earnings': {'EN': '💰 Earnings', 'HI': '💰 कमाई'},
    '📊 Workforce Utilization': {'EN': '📊 Workforce Utilization', 'HI': '📊 कार्यबल उपयोग'},
    'Incoming Requests': {'EN': 'Incoming Requests', 'HI': 'आने वाले अनुरोध'},
    'View All Requests →': {'EN': 'View All Requests →', 'HI': 'सभी अनुरोध देखें →'},
    'Workforce Overview': {'EN': 'Workforce Overview', 'HI': 'कार्यबल अवलोकन'},
    'Manage Workers →': {'EN': 'Manage Workers →', 'HI': 'श्रमिकों का प्रबंधन करें →'},
    'Available': {'EN': 'Available', 'HI': 'उपलब्ध'},
    'Working': {'EN': 'Working', 'HI': 'कार्यरत'},
    'Assigned': {'EN': 'Assigned', 'HI': 'सौंपा गया'},
    'Unavailable': {'EN': 'Unavailable', 'HI': 'अनुपलब्ध'},
    'WORKFORCE INSIGHT': {'EN': 'WORKFORCE INSIGHT', 'HI': 'कार्यबल अंतर्दृष्टि'},
    'Confidence: 82%': {'EN': 'Confidence: 82%', 'HI': 'विश्वास: 82%'},
    'Painting demand is expected to increase by 24% next week.': {'EN': 'Painting demand is expected to increase by 24% next week.', 'HI': 'अगले सप्ताह पेंटिंग की मांग 24% बढ़ने की उम्मीद है।'},
    'Consider adding 4–6 painting workers to your available pool.': {'EN': 'Consider adding 4–6 painting workers to your available pool.', 'HI': 'अपने उपलब्ध पूल में 4-6 पेंटिंग श्रमिकों को जोड़ने पर विचार करें।'},
    'Find nearby work opportunities, workforce support and shared equipment.': {'EN': 'Find nearby work opportunities, workforce support and shared equipment.', 'HI': 'आस-पास के काम के अवसर, कार्यबल सहायता और साझा उपकरण खोजें।'},
    'Explore Exchange →': {'EN': 'Explore Exchange →', 'HI': 'विनिमय का अन्वेषण करें →'},
    'Residential Painting': {'EN': 'Residential Painting', 'HI': 'आवासीय पेंटिंग'},
    'Dwarka • Household': {'EN': 'Dwarka • Household', 'HI': 'द्वारका • घरेलू'},
    'New': {'EN': 'New', 'HI': 'नया'},
    'Sep 12 • 2 workers': {'EN': 'Sep 12 • 2 workers', 'HI': '12 सितंबर • 2 श्रमिक'},
    'Community Hall Repair': {'EN': 'Community Hall Repair', 'HI': 'सामुदायिक हॉल की मरम्मत'},
    'Najafgarh • Institution': {'EN': 'Najafgarh • Institution', 'HI': 'नजफगढ़ • संस्थान'},
    'Urgent': {'EN': 'Urgent', 'HI': 'अति आवश्यक'},
    'Sep 18–22 • 5 workers': {'EN': 'Sep 18–22 • 5 workers', 'HI': '18-22 सितंबर • 5 श्रमिक'},
    'View Request →': {'EN': 'View Request →', 'HI': 'अनुरोध देखें →'},

    // Role Selection Screen
    'Step 2 / 2': {'EN': 'Step 2 / 2', 'HI': 'चरण 2 / 2'},
    'How will you use SAHYOG?': {'EN': 'How will you use SAHYOG?', 'HI': 'अपनी भूमिका चुनें'},
    'Choose your role to get started': {'EN': 'Choose your role to get started', 'HI': 'आप SAHYOG का उपयोग किस रूप में करना चाहते हैं?'},
    'Worker': {'EN': 'Worker', 'HI': 'श्रमिक'},
    'कामगार': {'EN': 'कामगार', 'HI': 'कामगार'},
    'Find work, manage skills & track earnings': {'EN': 'Find work, manage skills & track earnings', 'HI': 'काम खोजें, कौशल प्रबंधित करें और कमाई ट्रैक करें'},
    'Cooperative': {'EN': 'Cooperative', 'HI': 'सहकारी समिति'},
    'सहकारी': {'EN': 'सहकारी', 'HI': 'गिल्ड / संस्था'},
    'Manage workers, jobs & opportunities': {'EN': 'Manage workers, jobs & opportunities', 'HI': 'श्रमिकों, काम और अवसरों का प्रबंधन करें'},
    'Institution': {'EN': 'Institution', 'HI': 'संस्था'},
    'संस्थान': {'EN': 'संस्थान', 'HI': 'व्यापार / निकाय'},
    'Find workforce for your requirements': {'EN': 'Find workforce for your requirements', 'HI': 'अपनी आवश्यकताओं के लिए कार्यबल खोजें'},
    'Household': {'EN': 'Household', 'HI': 'परिवार'},
    'परिवार': {'EN': 'परिवार', 'HI': 'नागरिक'},
    'Request trusted local services': {'EN': 'Request trusted local services', 'HI': 'विश्वसनीय स्थानीय सेवाओं का अनुरोध करें'},
    'You can link additional roles later in settings': {'EN': 'You can link additional roles later in settings', 'HI': 'आप बाद में सेटिंग्स से अन्य भूमिकाएँ भी जोड़ सकते हैं।'},

    // Worker Welcome Page
    'WORKER • कामगार': {'EN': 'WORKER • कामगार', 'HI': 'WORKER • कामगार'},
    'Welcome, Worker': {'EN': 'Welcome, Worker', 'HI': 'स्वागत है, कामगार'},
    'Create your profile. Get better work opportunities.': {'EN': 'Create your profile. Get better work opportunities.', 'HI': 'अपनी प्रोफ़ाइल बनाएं। बेहतर काम के अवसर पाएं।'},
    'Find the right work opportunities, show your skills, manage your work and see your earnings — all in one place.': {'EN': 'Find the right work opportunities, show your skills, manage your work and see your earnings — all in one place.', 'HI': 'सही काम के अवसर खोजें, अपनी कुशलताएँ दिखाएं, अपने काम संभालें और अपनी कमाई देखें — सब एक ही जगह।'},
    'With SAHYOG you': {'EN': 'With SAHYOG you', 'HI': 'SAHYOG के साथ आप'},
    'Create your Skill Passport': {'EN': 'Create your Skill Passport', 'HI': 'अपना Skill Passport बनाएं'},
    'Find the right work opportunities for yourself': {'EN': 'Find the right work opportunities for yourself', 'HI': 'अपने लिए सही काम के अवसर पाएं'},
    'Set your availability': {'EN': 'Set your availability', 'HI': 'अपनी उपलब्धता तय करें'},
    'View earnings and payment history': {'EN': 'View earnings and payment history', 'HI': 'कमाई और भुगतान का इतिहास देखें'},
    'Connect with your cooperative': {'EN': 'Connect with your cooperative', 'HI': 'अपनी सहकारी संस्था से जुड़ें'},
    'Your information is secure and used with your permission.': {'EN': 'Your information is secure and used with your permission.', 'HI': 'आपकी जानकारी सुरक्षित और आपकी अनुमति से उपयोग की जाती है।'},
    'Log in →': {'EN': 'Log in →', 'HI': 'लॉग इन करें →'},
    '+ Create Account': {'EN': '+ Create Account', 'HI': '+ खाता बनाएं'},
    'New to cooperatives?': {'EN': 'New to cooperatives?', 'HI': 'सहकारी संस्थाओं से नए हैं?'},
    'Start in 2 mins': {'EN': 'Start in 2 mins', 'HI': '2 मिनट में शुरू करें'},

    // Worker Registration Screen
    'Worker Registration • कामगार पंजीकरण': {'EN': 'Worker Registration • कामगार पंजीकरण', 'HI': 'कामगार पंजीकरण • Worker Registration'},
    'Create your worker profile': {'EN': 'Create your worker profile', 'HI': 'अपनी कामगार प्रोफ़ाइल बनाएं'},
    'Tell us a little about yourself to get started.': {'EN': 'Tell us a little about yourself to get started.', 'HI': 'शुरू करने के लिए अपने बारे में कुछ जानकारी दें।'},
    'Full Name': {'EN': 'Full Name', 'HI': 'पूरा नाम'},
    'Enter your full name': {'EN': 'Enter your full name', 'HI': 'अपना नाम दर्ज करें'},
    'Mobile Number': {'EN': 'Mobile Number', 'HI': 'मोबाइल नंबर'},
    'OTP Login': {'EN': 'OTP Login', 'HI': 'OTP Login'},
    'Enter 10-digit mobile': {'EN': 'Enter 10-digit mobile', 'HI': 'अपना मोबाइल नंबर दर्ज करें'},
    'We\'ll verify this with an SMS OTP in the next step': {'EN': 'We\'ll verify this with an SMS OTP in the next step', 'HI': 'हम अगले चरण में एसएमएस OTP द्वारा इसे सत्यापित करेंगे।'},
    'Location': {'EN': 'Location', 'HI': 'स्थान'},
    'Enter your city / area': {'EN': 'Enter your city / area', 'HI': 'अपना शहर या क्षेत्र दर्ज करें'},
    'Primary Skill': {'EN': 'Primary Skill', 'HI': 'मुख्य कुशलता'},
    'Select your main skill': {'EN': 'Select your main skill', 'HI': 'अपनी मुख्य कुशलता चुनें'},
    'Add more skills later from your Skill Passport.': {'EN': 'Add more skills later from your Skill Passport.', 'HI': 'आप बाद में अपने Skill Passport में और कुशलताएँ जोड़ सकते हैं।'},
    'Are you part of a cooperative?': {'EN': 'Are you part of a cooperative?', 'HI': 'क्या आप किसी सहकारी संस्था से जुड़े हैं?'},
    'Optional': {'EN': 'Optional', 'HI': 'वैकल्पिक'},
    'Cooperative membership is completely optional. You can always use SAHYOG independently.': {'EN': 'Cooperative membership is completely optional. You can always use SAHYOG independently.', 'HI': 'सहकारी सदस्यता पूरी तरह से वैकल्पिक है। आप हमेशा स्वतंत्र रूप से सहयोग का उपयोग कर सकते हैं।'},
    'Yes': {'EN': 'Yes', 'HI': 'हाँ'},
    'No': {'EN': 'No', 'HI': 'नहीं'},
    'Your information is protected and shared only with your consent.': {'EN': 'Your information is protected and shared only with your consent.', 'HI': 'आपकी जानकारी सुरक्षित और आपकी अनुमति से उपयोग की जाती है।'},

    // Worker Verification Screen
    'Identity Verification • ई-श्रम सत्यापन': {'EN': 'Identity Verification • ई-श्रम सत्यापन', 'HI': 'पहचान सत्यापन • e-Shram Verification'},
    'Verify your identity': {'EN': 'Verify your identity', 'HI': 'अपनी पहचान सत्यापित करें'},
    'Verify your details using your e-Shram record.': {'EN': 'Verify your details using your e-Shram record.', 'HI': 'अपने e-Shram रिकॉर्ड की मदद से अपनी जानकारी सत्यापित करें।'},
    'National Social Security (UAN)': {'EN': 'National Social Security (UAN)', 'HI': 'राष्ट्रीय सामाजिक सुरक्षा (UAN)'},
    'GOVT': {'EN': 'GOVT', 'HI': 'भारत सरकार / GOVT'},
    'Connects your Skill Passport and cooperative gig benefits.': {'EN': 'Connects your Skill Passport and cooperative gig benefits.', 'HI': 'आपके Skill Passport और सहकारी कामगार लाभों को जोड़ता है।'},
    'e-Shram UAN (Universal Account Number)': {'EN': 'e-Shram UAN (Universal Account Number)', 'HI': 'e-Shram UAN (यूनिवर्सल अकाउंट नंबर)'},
    'Enter your 12-digit UAN': {'EN': 'Enter your 12-digit UAN', 'HI': 'अपना 12 अंकों का UAN दर्ज करें'},
    'Example: 1234 5678 9012': {'EN': 'Example: 1234 5678 9012', 'HI': 'उदाहरण: 1234 5678 9012'},
    'Fill Sample': {'EN': 'Fill Sample', 'HI': 'नमूना भरें'},
    'I consent to verify my details through e-Shram.': {'EN': 'I consent to verify my details through e-Shram.', 'HI': 'मैं e-Shram के माध्यम से अपनी जानकारी सत्यापित करने की अनुमति देता/देती हूँ।'},
    'Verify with e-Shram →': {'EN': 'Verify with e-Shram →', 'HI': 'e-Shram से सत्यापित करें →'},
    'Skip for now': {'EN': 'Skip for now', 'HI': 'अभी छोड़ें'},
    'Consent-Based Identity Verification': {'EN': 'Consent-Based Identity Verification', 'HI': 'सहमति-आधारित पहचान सत्यापन'},
    'Your information is used only with your consent. SAHYOG protects your worker rights and privacy.': {'EN': 'Your information is used only with your consent. SAHYOG protects your worker rights and privacy.', 'HI': 'आपकी जानकारी केवल आपकी अनुमति से उपयोग की जाती है। SAHYOG आपके कामगार अधिकारों और गोपनीयता की रक्षा करता है।'},

    // Skill Passport Screen
    'Worker Profile • कौशल पासपोर्ट': {'EN': 'Worker Profile • कौशल पासपोर्ट', 'HI': 'Worker Profile • कौशल पासपोर्ट'},
    'Build your Skill Passport': {'EN': 'Build your Skill Passport', 'HI': 'अपना Skill Passport बनाएं'},
    'Tell us about your skills and experience to find better work opportunities.': {'EN': 'Tell us about your skills and experience to find better work opportunities.', 'HI': 'अपनी कुशलताओं और अनुभव के बारे में बताएं ताकि आपको बेहतर काम के अवसर मिल सकें।'},
    'Verified Digital Credential': {'EN': 'Verified Digital Credential', 'HI': 'डिजिटल सत्यापन प्रमाण'},
    'CIVIC': {'EN': 'CIVIC', 'HI': 'सत्यापित'},
    'Recognized across all registered cooperatives.': {'EN': 'Recognized across all registered cooperatives.', 'HI': 'पंजीकृत सहकारी संस्थाओं द्वारा मान्य'},
    'YOUR SKILLS': {'EN': 'YOUR SKILLS', 'HI': 'मुख्य कुशलता'},
    'Primary required': {'EN': 'Primary required', 'HI': 'मुख्य कुशलता आवश्यक'},
    'Select your primary skill': {'EN': 'Select your primary skill', 'HI': 'अपनी मुख्य कुशलता चुनें'},
    'Other skills (optional)': {'EN': 'Other skills (optional)', 'HI': 'अन्य कुशलताएँ (वैकल्पिक)'},
    'Add other skills (e.g. Tile fixing, Welding)': {'EN': 'Add other skills (e.g. Tile fixing, Welding)', 'HI': 'अन्य कुशलताएँ जोड़ें (उदा. टाइल लगाना, वेल्डिंग)'},
    'EXPERIENCE': {'EN': 'EXPERIENCE', 'HI': 'अनुभव'},
    'YEARS IN TRADE': {'EN': 'YEARS IN TRADE', 'HI': 'व्यवसाय में वर्षों का अनुभव'},
    'e.g. 5 years': {'EN': 'e.g. 5 years', 'HI': 'उदा. 5 वर्ष'},
    'Years': {'EN': 'Years', 'HI': 'वर्ष'},
    'ABOUT YOUR WORK': {'EN': 'ABOUT YOUR WORK', 'HI': 'अपने काम के बारे में'},
    'Briefly describe your experience (e.g., worked on residential renovation for 4 years)': {'EN': 'Briefly describe your experience (e.g., worked on residential renovation for 4 years)', 'HI': 'अपने अनुभव के बारे में संक्षेप में बताएं (उदा. आवासीय नवीनीकरण और निर्माण में 4 साल का काम किया है)'},
    '⚡ Fill Sample': {'EN': '⚡ Fill Sample', 'HI': '⚡ नमूना भरें'},
    'You can update your skills anytime from your Skill Passport.': {'EN': 'You can update your skills anytime from your Skill Passport.', 'HI': 'आप अपना Skill Passport कभी भी अपडेट कर सकते हैं।'},
    'Create Skill Passport →': {'EN': 'Create Skill Passport →', 'HI': 'Skill Passport बनाएं →'},

    // OTP Screen

    // OTP Screen
    'WORKER • ओटीपी सत्यापन': {'EN': 'WORKER • OTP Verification', 'HI': 'कामगार • ओटीपी सत्यापन'},
    'COOPERATIVE ADMIN • ओटीपी सत्यापन': {'EN': 'COOPERATIVE ADMIN • OTP Verification', 'HI': 'सहकारी एडमिन • ओटीपी सत्यापन'},
    'Verify your mobile number': {'EN': 'Verify your mobile number', 'HI': 'अपना मोबाइल नंबर सत्यापित करें'},
    'Enter the 6-digit OTP sent to ': {'EN': 'Enter the 6-digit OTP sent to ', 'HI': 'इस नंबर पर भेजा गया 6 अंकों का OTP दर्ज करें '},
    'SECURITY PIN': {'EN': 'SECURITY PIN', 'HI': 'सुरक्षा पिन'},
    'Incorrect OTP. Please check the code or click resend below.': {'EN': 'Incorrect OTP. Please check the code or click resend below.', 'HI': 'गलत OTP. कृपया कोड जांचें या नीचे पुनः भेजें पर क्लिक करें।'},
    'Test Demo OTP (794258)': {'EN': 'Test Demo OTP (794258)', 'HI': 'डेमो OTP भरें (794258)'},
    'Clear': {'EN': 'Clear', 'HI': 'साफ करें'},
    'Verify & Continue →': {'EN': 'Verify & Continue →', 'HI': 'सत्यापित करें और जारी रखें →'},
    'Didn\'t receive the OTP?': {'EN': 'Didn\'t receive the OTP?', 'HI': 'क्या OTP नहीं मिला?'},
    'Resend OTP in 00:30': {'EN': 'Resend OTP in 00:30', 'HI': '00:30 में पुनः भेजें'},
    'Authorized Representative Verification\n': {'EN': 'Authorized Representative Verification\n', 'HI': 'अधिकृत प्रतिनिधि सत्यापन\n'},
    'This OTP verifies the registered administrator mobile number under SAHYOG Digital Public Infrastructure. Cooperative entity verification occurs on the next step.': {'EN': 'This OTP verifies the registered administrator mobile number under SAHYOG Digital Public Infrastructure. Cooperative entity verification occurs on the next step.', 'HI': 'यह OTP SAHYOG डिजिटल पब्लिक इंफ्रास्ट्रक्चर के तहत पंजीकृत एडमिन मोबाइल नंबर को सत्यापित करता है।'},

    // Worker Main Layout
    'Home': {'EN': 'Home', 'HI': 'होम'},
    'Jobs': {'EN': 'Jobs', 'HI': 'काम'},
    'Skill Passport': {'EN': 'Skill Passport', 'HI': 'Skill Passport'},
    'Earnings': {'EN': 'Earnings', 'HI': 'कमाई'},
    'Profile': {'EN': 'Profile', 'HI': 'प्रोफ़ाइल'},

    // Worker Dashboard Screen
    'COOPERATIVE GUILD\nWorker Portal': {'EN': 'COOPERATIVE GUILD\nWorker Portal', 'HI': 'सहकारी गिल्ड\nकामगार पोर्टल'},
    'Good morning, Ramlal 👋': {'EN': 'Good morning, Ramlal 👋', 'HI': 'सुप्रभात, रामलाल 👋'},
    'Here\'s what\'s happening with your work today.': {'EN': 'Here\'s what\'s happening with your work today.', 'HI': 'आज आपके काम से जुड़ी जानकारी यहां है।'},
    'Ramlal Kumar': {'EN': 'Ramlal Kumar', 'HI': 'रामलाल कुमार'},
    'Construction Worker\n(Masonry & Painting)': {'EN': 'Construction Worker\n(Masonry & Painting)', 'HI': 'निर्माण कामगार\n(पेंटिंग और राजमिस्त्री)'},
    'ID Card': {'EN': 'ID Card', 'HI': 'ID Card'},
    'e-Shram Verified': {'EN': 'e-Shram Verified', 'HI': 'e-Shram सत्यापित'},
    'UAN •••• 9012': {'EN': 'UAN •••• 9012', 'HI': 'UAN •••• 9012'},
    'Skill Passport Active': {'EN': 'Skill Passport Active', 'HI': 'Skill Passport सक्रिय'},
    'Level 2 Certified': {'EN': 'Level 2 Certified', 'HI': 'लेवल 2 प्रमाणित'},
    'TODAY\'S WORK': {'EN': 'TODAY\'S WORK', 'HI': 'आज का काम'},
    '1 Active Gig': {'EN': '1 Active Gig', 'HI': '1 सक्रिय काम'},
    'Household Gig': {'EN': 'Household Gig', 'HI': 'घरेलू काम'},
    'Confirmed': {'EN': 'Confirmed', 'HI': 'पुष्टि हो गई'},
    'Painting Work': {'EN': 'Painting Work', 'HI': 'पेंटिंग का काम'},
    'Today • 10:00 AM': {'EN': 'Today • 10:00 AM', 'HI': 'आज • सुबह 10:00 बजे'},
    'Full Day Shift': {'EN': 'Full Day Shift', 'HI': 'पूरा दिन'},
    'Dwarka, Delhi': {'EN': 'Dwarka, Delhi', 'HI': 'द्वारका, दिल्ली'},
    'FIXED COOPERATIVE RATE:': {'EN': 'FIXED COOPERATIVE RATE:', 'HI': 'सहकारी निश्चित दर:'},
    '₹ 850': {'EN': '₹ 850', 'HI': '₹ 850'},
    ' / day': {'EN': ' / day', 'HI': ' / दिन'},
    'View Job →': {'EN': 'View Job →', 'HI': 'काम देखें →'},
    'UPCOMING JOBS': {'EN': 'UPCOMING JOBS', 'HI': 'आने वाले काम'},
    'See All (2)': {'EN': 'See All (2)', 'HI': 'सभी देखें (2)'},
    'Tomorrow • 9:00 AM': {'EN': 'Tomorrow • 9:00 AM', 'HI': 'कल • सुबह 9:00 बजे'},
    'Vasant Kunj': {'EN': 'Vasant Kunj', 'HI': 'वसंत कुंज'},
    '18 Sep • 10:00 AM': {'EN': '18 Sep • 10:00 AM', 'HI': '18 सितम्बर • सुबह 10:00 बजे'},
    'Rohini, Sector 7': {'EN': 'Rohini, Sector 7', 'HI': 'रोहिणी, सेक्टर 7'},
    'QUICK ACCESS': {'EN': 'QUICK ACCESS', 'HI': 'क्विक एक्सेस'},
    'My Skills': {'EN': 'My Skills', 'HI': 'मेरी कुशलताएँ'},
    'Passport & Badges': {'EN': 'Passport & Badges', 'HI': 'पासपोर्ट और प्रमाणपत्र'},
    '₹ 14,200 this month': {'EN': '₹ 14,200 this month', 'HI': 'इस महीने ₹ 14,200'},
    'Payment History': {'EN': 'Payment History', 'HI': 'भुगतान इतिहास'},
    'Direct Bank Transfers': {'EN': 'Direct Bank Transfers', 'HI': 'सीधा बैंक ट्रांसफर'},
    'Availability': {'EN': 'Availability', 'HI': 'उपलब्धता'},
    'Ready for Work •': {'EN': 'Ready for Work •', 'HI': 'काम के लिए तैयार •'},
    'Cooperative Member Protection:': {'EN': 'Cooperative Member Protection:', 'HI': 'सहकारी सुरक्षा गारंटी:'},
    ' Guaranteed fair minimum wage and on-site insurance provided by your guild.': {'EN': ' Guaranteed fair minimum wage and on-site insurance provided by your guild.', 'HI': ' आपकी गिल्ड द्वारा तय किया गया न्यूनतम पारिश्रमिक और कार्यस्थल बीमा सुनिश्चित है।'},

    // Worker Jobs Screen
    'New Work Opportunity': {'EN': 'New Work Opportunity', 'HI': 'नया काम का अवसर'},
    '1 Direct Guild Invite': {'EN': '1 Direct Guild Invite', 'HI': '1 • प्रत्यक्ष गिल्ड आमंत्रण'},
    'You\'ve been selected for a new project.': {'EN': 'You\'ve been selected for a new project.', 'HI': 'आपको एक नए प्रोजेक्ट के लिए चुना गया है।'},
    'Dispatched under formal cooperative collective standards.': {'EN': 'Dispatched under formal cooperative collective standards.', 'HI': 'औपचारिक सहकारी गिल्ड सामूहिक मानकों के तहत प्रेषित।'},
    'Nirman Shramik Cooperative': {'EN': 'Nirman Shramik Cooperative', 'HI': 'निर्माण श्रमिक सहकारी संस्था'},
    'Verified Cooperative ✓': {'EN': 'Verified Cooperative ✓', 'HI': 'सत्यापित सहकारी संस्था ✓'},
    'Your skills match this opportunity.': {'EN': 'Your skills match this opportunity.', 'HI': 'आपकी कुशलताएँ इस अवसर के लिए उपयुक्त हैं।'},
    'Institutional Project': {'EN': 'Institutional Project', 'HI': 'संस्थागत प्रोजेक्ट'},
    'Community Hall Renovation': {'EN': 'Community Hall Renovation', 'HI': 'सामुदायिक भवन मरम्मत'},
    'Dates': {'EN': 'Dates', 'HI': 'तिथियां'},
    '18 Sep – 22 Sep': {'EN': '18 Sep – 22 Sep', 'HI': '18-22 सितम्बर'},
    'Shift Timing': {'EN': 'Shift Timing', 'HI': 'शिफ्ट समय'},
    '9:00 AM – 5:00 PM': {'EN': '9:00 AM – 5:00 PM', 'HI': 'सुबह 9:00 - शाम 5:00'},
    'Team Scale': {'EN': 'Team Scale', 'HI': 'टीम का आकार'},
    '5 workers required': {'EN': '5 workers required', 'HI': '5 कामगारों की आवश्यकता'},
    'YOUR ROLE': {'EN': 'YOUR ROLE', 'HI': 'आपकी भूमिका'},
    'Masonry & Painting Worker': {'EN': 'Masonry & Painting Worker', 'HI': 'राजमिस्त्री और पेंटिंग कामगार'},
    '5 Days': {'EN': '5 Days', 'HI': '5 दिन'},
    'ESTIMATED EARNINGS': {'EN': 'ESTIMATED EARNINGS', 'HI': 'अनुमानित कमाई'},
    'Guaranteed ₹1,200/day': {'EN': 'Guaranteed ₹1,200/day', 'HI': 'गारंटीकृत ₹1,200/दिन'},
    '₹6,000': {'EN': '₹6,000', 'HI': '₹6,000'},
    '(5 Days collective shift)': {'EN': '(5 Days collective shift)', 'HI': '(5 दिनों की सामूहिक शिफ्ट)'},
    'Final payment will be recorded after project completion.': {'EN': 'Final payment will be recorded after project completion.', 'HI': 'अंतिम भुगतान काम पूरा होने के बाद दर्ज किया जाएगा।'},
    'WHY YOU WERE SELECTED': {'EN': 'WHY YOU WERE SELECTED', 'HI': 'आपको क्यों चुना गया'},
    'Your Skill Passport matches the masonry and painting requirements for this project.': {'EN': 'Your Skill Passport matches the masonry and painting requirements for this project.', 'HI': 'आपका Skill Passport इस प्रोजेक्ट की राजमिस्त्री और पेंटिंग की आवश्यकताओं से मेल खाता है।'},
    'You can review the project details before accepting.': {'EN': 'You can review the project details before accepting.', 'HI': 'स्वीकार करने से पहले आप प्रोजेक्ट की पूरी जानकारी देख सकते हैं।'},
    '✓ Accept Opportunity': {'EN': '✓ Accept Opportunity', 'HI': '✓ अवसर स्वीकार करें'},
    'Decline': {'EN': 'Decline', 'HI': 'अस्वीकार करें'},

    // Login Options Screen
    'Welcome Back': {'EN': 'Welcome Back', 'HI': 'वापसी पर स्वागत है'},
    'Login to manage your cooperative and workforce': {'EN': 'Login to manage your cooperative and workforce', 'HI': 'अपनी सहकारी संस्था और कार्यबल का प्रबंधन करने के लिए लॉगिन करें'},
    'COOPERATIVE ADMIN': {'EN': 'COOPERATIVE ADMIN', 'HI': 'सहकारी व्यवस्थापक'},
    'Admin Mobile Number': {'EN': 'Admin Mobile Number', 'HI': 'व्यवस्थापक मोबाइल नंबर'},
    'Enter admin mobile number': {'EN': 'Enter admin mobile number', 'HI': 'व्यवस्थापक मोबाइल नंबर दर्ज करें'},
    "We'll send a one-time password (OTP) to the authorized representative.": {'EN': "We'll send a one-time password (OTP) to the authorized representative.", 'HI': 'हम अधिकृत प्रतिनिधि को एक वन-टाइम पासवर्ड (OTP) भेजेंगे।'},
    'Send OTP': {'EN': 'Send OTP', 'HI': 'ओटीपी भेजें'},
    'OR': {'EN': 'OR', 'HI': 'या'},
    'Continue with Cooperative ID': {'EN': 'Continue with Cooperative ID', 'HI': 'सहकारी आईडी के साथ जारी रखें'},
    'Cooperative ID Login': {'EN': 'Cooperative ID Login', 'HI': 'सहकारी आईडी लॉगिन'},
    'Back to Mobile': {'EN': 'Back to Mobile', 'HI': 'मोबाइल पर वापस जाएं'},
    'Registration / Cooperative ID': {'EN': 'Registration / Cooperative ID', 'HI': 'पंजीकरण / सहकारी आईडी'},
    'Authorized Signatory PIN / Password': {'EN': 'Authorized Signatory PIN / Password', 'HI': 'अधिकृत हस्ताक्षरकर्ता पिन / पासवर्ड'},
    'Verify & Login': {'EN': 'Verify & Login', 'HI': 'सत्यापित करें और लॉगिन करें'},
    'For registered state federations and cooperative societies under MSCS Act.': {'EN': 'For registered state federations and cooperative societies under MSCS Act.', 'HI': 'MSCS अधिनियम के तहत पंजीकृत राज्य संघों और सहकारी समितियों के लिए।'},
    'Authorized Representative Access: ': {'EN': 'Authorized Representative Access: ', 'HI': 'अधिकृत प्रतिनिधि पहुंच: '},
    'Secure authentication for registered cooperatives under SAHYOG DPI network.': {'EN': 'Secure authentication for registered cooperatives under SAHYOG DPI network.', 'HI': 'सहयोग डीपीआई नेटवर्क के तहत पंजीकृत सहकारी समितियों के लिए सुरक्षित प्रमाणीकरण।'},

    // Profile Screen
    'Cooperative Profile': {'EN': 'Cooperative Profile', 'HI': 'सहकारी प्रोफ़ाइल'},
    'Manage cooperative information, settings and verification.': {'EN': 'Manage cooperative information, settings and verification.', 'HI': 'सहकारी जानकारी, सेटिंग्स और सत्यापन का प्रबंधन करें।'},
    'Reg: COOP-DL-2026-0142': {'EN': 'Reg: COOP-DL-2026-0142', 'HI': 'पंजीकरण: COOP-DL-2026-0142'},
    '✓ Verified': {'EN': '✓ Verified', 'HI': '✓ सत्यापित'},
    'Location:': {'EN': 'Location:', 'HI': 'स्थान:'},
    'Dwarka, New Delhi': {'EN': 'Dwarka, New Delhi', 'HI': 'द्वारका, नई दिल्ली'},
    'Service Areas:': {'EN': 'Service Areas:', 'HI': 'सेवा क्षेत्र:'},
    'Dwarka • Najafgarh • West Delhi': {'EN': 'Dwarka • Najafgarh • West Delhi', 'HI': 'द्वारका • नजफगढ़ • पश्चिम दिल्ली'},
    'PRIMARY SERVICES': {'EN': 'PRIMARY SERVICES', 'HI': 'प्राथमिक सेवाएं'},
    'Profile status active': {'EN': 'Profile status active', 'HI': 'प्रोफ़ाइल स्थिति सक्रिय'},
    'Edit Profile': {'EN': 'Edit Profile', 'HI': 'प्रोफ़ाइल संपादित करें'},
    'AUTHORIZED REPRESENTATIVE': {'EN': 'AUTHORIZED REPRESENTATIVE', 'HI': 'अधिकृत प्रतिनिधि'},
    'Personal details for registered cooperative account': {'EN': 'Personal details for registered cooperative account', 'HI': 'पंजीकृत सहकारी खाते के लिए व्यक्तिगत विवरण'},
    'Admin Name:': {'EN': 'Admin Name:', 'HI': 'व्यवस्थापक का नाम:'},
    'Rajesh Kumar': {'EN': 'Rajesh Kumar', 'HI': 'राजेश कुमार'},
    'Role:': {'EN': 'Role:', 'HI': 'भूमिका:'},
    'Cooperative Administrator': {'EN': 'Cooperative Administrator', 'HI': 'सहकारी प्रशासक'},
    'Mobile:': {'EN': 'Mobile:', 'HI': 'मोबाइल:'},
    'Email:': {'EN': 'Email:', 'HI': 'ईमेल:'},
    'Edit Admin Details': {'EN': 'Edit Admin Details', 'HI': 'व्यवस्थापक विवरण संपादित करें'},
    'COOPERATIVE SETTINGS': {'EN': 'COOPERATIVE SETTINGS', 'HI': 'सहकारी सेटिंग्स'},
    'Preferences': {'EN': 'Preferences', 'HI': 'प्राथमिकताएं'},
    'Notifications': {'EN': 'Notifications', 'HI': 'सूचनाएं'},
    'Request and payment updates': {'EN': 'Request and payment updates', 'HI': 'अनुरोध और भुगतान अपडेट'},
    'Service Areas': {'EN': 'Service Areas', 'HI': 'सेवा क्षेत्र'},
    'Manage locations served': {'EN': 'Manage locations served', 'HI': 'प्रदान किए गए स्थानों का प्रबंधन करें'},
    'Language': {'EN': 'Language', 'HI': 'भाषा'},
    'English (हिन्दी available)': {'EN': 'English (हिन्दी available)', 'HI': 'English (हिन्दी available)'},
    'COOPERATIVE VERIFICATION': {'EN': 'COOPERATIVE VERIFICATION', 'HI': 'सहकारी सत्यापन'},
    'Government of NCT Delhi Compliance': {'EN': 'Government of NCT Delhi Compliance', 'HI': 'एनसीटी दिल्ली सरकार का अनुपालन'},
    'Approved': {'EN': 'Approved', 'HI': 'स्वीकृत'},
    'Mobile Number Verified': {'EN': 'Mobile Number Verified', 'HI': 'मोबाइल नंबर सत्यापित'},
    'Aug 2026': {'EN': 'Aug 2026', 'HI': 'अगस्त 2026'},
    'Registration Details Submitted': {'EN': 'Registration Details Submitted', 'HI': 'पंजीकरण विवरण जमा किया गया'},
    'Cooperative Society Verified': {'EN': 'Cooperative Society Verified', 'HI': 'सहकारी समिति सत्यापित'},
    'Sep 2026': {'EN': 'Sep 2026', 'HI': 'सितंबर 2026'},
    'View Verification Certificate & Details ↓': {'EN': 'View Verification Certificate & Details ↓', 'HI': 'सत्यापन प्रमाणपत्र और विवरण देखें ↓'},
    'Log Out': {'EN': 'Log Out', 'HI': 'लॉग आउट'},
  };
}
